INSERT INTO Customers (customer_id,first_name,last_name,email) VALUES (301,'Sam','N','sam@gmail.com');
INSERT INTO Customers (customer_id,first_name,last_name,email) VALUES (302,'Ram','D','DeeRam@gmail.com');
INSERT INTO Customers (customer_id,first_name,last_name,email) VALUES (303,'Pavan','K','pavan459@gmail.com');
INSERT INTO Customers (customer_id,first_name,last_name,email) VALUES (304,'Sita','P','sita2001@gmail.com');
INSERT INTO Customers (customer_id,first_name,last_name,email) VALUES (305,'Gita','V','artistno1@gmail.com');
INSERT INTO Customers (customer_id,first_name,last_name,email) VALUES (306,'Sai Kumar','B','Kumarrocks@hotmail.com');
INSERT INTO Customers (customer_id,first_name,last_name,email) VALUES (307,'Sumanth','P','single4life@gmail.com');
DELETE FROM Customers WHERE customer_id = 304;
DELETE FROM Customers WHERE customer_id = 306;
SELECT customer_id FROM Customers;
