SELECT COUNT(*)
FROM PASSENGER p, RESERVATION r, FLIGHT F, AIRLINE a
WHERE
    a.AIRLINENAME = "United Airways" AND
    a.AIRLINECODE = f.AIRLINECODE AND
    f.FLIGHTNUMBER = r.FLIGHTNUMBER AND
    r.RESERVATIONID = p.RESERVATIONID;
